# Generated by Django 3.2.18 on 2023-02-17 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=100)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('img', models.ImageField(upload_to='')),
                ('body', models.TextField()),
                ('show', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.author')),
                ('categories', models.ManyToManyField(to='blog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPM', 'Spam')], default='SPM', max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Low'), (2, 'NotRecommended'), (3, 'Normal'), (4, 'Recommended'), (5, 'HighlyRecommended')], default=None, null=True)),
                ('show', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
