# Generated by Django 3.2.18 on 2023-03-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogBI', '0001_initial'),
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='blogBI.IPAddress', verbose_name='ویو ها'),
        ),
    ]
