# Generated by Django 3.2.18 on 2023-02-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_date_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostReport',
        ),
    ]
