# Generated by Django 3.2.18 on 2023-02-23 13:26

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to=blog.models.user_directory_path),
        ),
    ]
