# Generated by Django 3.2.18 on 2023-02-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_joined',
        ),
    ]
