# Generated by Django 3.2.18 on 2023-02-24 15:41

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_author_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=user.models.profimage_image_directory_path),
        ),
    ]
